manifestVersion = 0

[package]
  type = "modpack"
  name = "fettlol"
  description = "The Fettlol Modpack, an opinionated Vanilla++ Experience."
  version = "1.14.4"
  platform = "fabric"
  license = "MIT"
  author = "Breki Tomasson <breki.tomasson@gmail.com>"

[requirements]
  minecraft = "1.17"
  fabric = "*"

[dependencies]
  advancements-debug = "https://www.brekitomasson.com/fettlol/mods/advdebug-2.3.0.jar"
  architectury = "https://www.brekitomasson.com/fettlol/mods/architectury-2.0.8-fabric.jar"
  autopath = "https://www.brekitomasson.com/fettlol/mods/autopath-mc1.17-1.4.3.jar"
  axesareweapons = "https://www.brekitomasson.com/fettlol/mods/AxesAreWeapons-1.2-1.17.jar"
  bedspreads = "https://www.brekitomasson.com/fettlol/mods/bedspreads-fabric-1.4.0-1.17.jar"
  beenfo = "https://www.brekitomasson.com/fettlol/mods/beenfo-1.17-fabric0.34.9-1.3.1.jar"
  better-dropped-items = "https://www.brekitomasson.com/fettlol/mods/betterdroppeditems-1.3.0-1.17.jar"
  blame = "https://www.brekitomasson.com/fettlol/mods/blame-1.17-4.0.0-fabric.jar"
  builtin-servers = "https://www.brekitomasson.com/fettlol/mods/builtin-servers-1.0.1-BETA+1.17.jar"
  cloth-config = "https://www.brekitomasson.com/fettlol/mods/cloth-config-5.0.34-fabric.jar"
  coloredslime = "https://www.brekitomasson.com/fettlol/mods/coloredslime-1.2.2+1.17.jar"
  croptopia = "https://www.brekitomasson.com/fettlol/mods/Croptopia-1.17-rc2-FABRIC-1.4.1.jar"
  damagetilt = "https://www.brekitomasson.com/fettlol/mods/DamageTilt-1.17-fabric-0.1.2.jar"
  dankstorage = "https://www.brekitomasson.com/fettlol/mods/dankstorage-2.0a-1.17.jar"
  dark-loading-screen = "https://www.brekitomasson.com/fettlol/mods/dark-loading-screen-1.6.4.jar"
  discerning-furnace = "https://www.brekitomasson.com/fettlol/mods/discerning-furnace-1.0.2+MC1.17.jar"
  ducts = "https://www.brekitomasson.com/fettlol/mods/ducts-1.1.0.jar"
  earth2java = "https://www.brekitomasson.com/fettlol/mods/Earth2Java-1.7.1+1.17.jar"
  emotecraft = "https://www.brekitomasson.com/fettlol/mods/emotecraft-for-MC1.17-rc2-2.0.5-fabric.jar"
  expandedstorage = "https://www.brekitomasson.com/fettlol/mods/expandedstorage-7.0.0-alpha.25+1.17.jar"
  fabric-api = "https://www.brekitomasson.com/fettlol/mods/fabric-api-0.35.1+1.17.jar"
  fabric-language-kotlin = "https://www.brekitomasson.com/fettlol/mods/fabric-language-kotlin-1.5.0+kotlin.1.4.31.jar"
  fallingleaves = "https://www.brekitomasson.com/fettlol/mods/fallingleaves-1.7.0+1.17.jar"
  fallingtree = "https://www.brekitomasson.com/fettlol/mods/FallingTree-1.17-2.11.5.jar"
  fettlol-utilmod = "https://www.brekitomasson.com/fettlol/mods/FettLolUtilMod-1.1.0+1.17.jar"
  geckolib = "https://www.brekitomasson.com/fettlol/mods/geckolib-fabric-1.17-3.0.5.jar"
  horsestatsvanilla = "https://www.brekitomasson.com/fettlol/mods/horse-stats-vanilla-4.1.8.jar"
  infinitywaterbucket = "https://www.brekitomasson.com/fettlol/mods/infinity-water-bucket-1.4-mc1.17-fabric.jar"
  keepheadnames = "https://www.brekitomasson.com/fettlol/mods/KeepHeadNames-1.3.jar"
  krypton = "https://www.brekitomasson.com/fettlol/mods/krypton-0.1.3.jar"
  lambdynamiclights = "https://www.brekitomasson.com/fettlol/mods/lambdynamiclights-2.0.0+1.17.jar"
  lightoverlay = "https://www.brekitomasson.com/fettlol/mods/light-overlay-6.0.0-fabric.jar"
  lithium = "https://www.brekitomasson.com/fettlol/mods/lithium-fabric-mc1.17-0.7.0.jar"
  mcdunegeonsweapons = "https://www.brekitomasson.com/fettlol/mods/mcdw-3.2.2-1.17.jar"
  mcdungeonsarmors = "https://www.brekitomasson.com/fettlol/mods/mcda-1.6.2.jar"
  midas-hunger = "https://www.brekitomasson.com/fettlol/mods/midas-hunger-1.4.0.jar"
  modmenu = "https://www.brekitomasson.com/fettlol/mods/modmenu-2.0.2.jar"  
  moreberries = "https://www.brekitomasson.com/fettlol/mods/moreberries-1.4.2.jar"
  morevillagers = "https://www.brekitomasson.com/fettlol/mods/morevillagers-FABRIC-1.17-2.0.0.jar"
  not-enough-animations = "https://www.brekitomasson.com/fettlol/mods/notenoughanimations-1.3.0.jar"
  npcvariety = "https://www.brekitomasson.com/fettlol/mods/npc-variety-1.17.0-2.0.0.jar"
  packages = "https://www.brekitomasson.com/fettlol/mods/packages-1.17-1.2.0.jar"
  perfectaccuracy = "https://www.brekitomasson.com/fettlol/mods/PerfectAccuracy-1.1-1.17.jar"
  presence-footsteps = "https://www.brekitomasson.com/fettlol/mods/PresenceFootsteps-r31-1.17-rc1.jar"
  ringofattraction = "https://www.brekitomasson.com/fettlol/mods/RingOfAttraction-Fabric-1.17-1.1.9.jar"
  riverredux = "https://www.brekitomasson.com/fettlol/mods/riverredux-0.2.0.jar"
  roughlyenoughitems = "https://www.brekitomasson.com/fettlol/mods/RoughlyEnoughItems-6.0.251-alpha-fabric.jar"
  seasons = "https://www.brekitomasson.com/fettlol/mods/fabric-seasons-1.2.2-BETA+1.17.jar"
  sheepconsistency = "https://www.brekitomasson.com/fettlol/mods/sheepconsistency-1.0.3.jar"
  spark = "https://www.brekitomasson.com/fettlol/mods/spark-fabric.jar"
  stoneholm = "https://www.brekitomasson.com/fettlol/mods/stoneholm-1.2.6.jar"
  taxfreelevels = "https://www.brekitomasson.com/fettlol/mods/TaxFreeLevels-1.2.jar"
  techreborn = "https://www.brekitomasson.com/fettlol/mods/TechReborn-5.0.1-beta+build.29.jar"
  transliterationlib = "https://www.brekitomasson.com/fettlol/mods/TRansliterationLib-1.1.0.jar"
  villagernames = "https://www.brekitomasson.com/fettlol/mods/villagernames-1.17-2.0.0.jar"
  waystones = "https://www.brekitomasson.com/fettlol/mods/wraith-waystones-2.0.1.jar"
  wthit = "https://www.brekitomasson.com/fettlol/mods/wthit-3.5.3-fabric.jar"

[dev]
