manifestVersion = 0

[package]
  type = "modpack"
  name = "fettlol"
  description = "The Fettlol Modpack, an opinionated Vanilla++ Experience."
  version = "1.14.4"
  platform = "fabric"
  license = "MIT"
  author = "Breki Tomasson <breki.tomasson@gmail.com>"

[requirements]
  minecraft = "1.17"
  fabric = "*"

[dependencies]
  architectury = "https://www.brekitomasson.com/fettlol/mods/architectury-2.0.7-fabric.jar"
  autopath = "https://www.brekitomasson.com/fettlol/mods/autopath-mc1.17-1.4.2.jar"
  axesareweapons = "https://www.brekitomasson.com/fettlol/mods/AxesAreWeapons-1.2-1.17.jar"
  builtin-servers = "https://www.brekitomasson.com/fettlol/mods/builtin-servers-1.0.1-BETA+1.17.jar"
  coloredslime = "https://www.brekitomasson.com/fettlol/mods/coloredslime-1.2.2+1.17.jar"
  croptopia = "https://www.brekitomasson.com/fettlol/mods/Croptopia-1.17-rc2-FABRIC-1.4.1.jar"
  dankstorage = "https://www.brekitomasson.com/fettlol/mods/dankstorage-2.0-1.17-rc1.jar"
  ducts = "https://www.brekitomasson.com/fettlol/mods/ducts-1.1.0.jar"
  earth2java = "https://www.brekitomasson.com/fettlol/mods/Earth2Java-1.7.1+1.17.jar"
  emotecraft = "https://www.brekitomasson.com/fettlol/mods/emotecraft-for-MC1.17-rc2-2.0.5-fabric.jar"
  expandedstorage = "https://www.brekitomasson.com/fettlol/mods/expandedstorage-7.0.0-alpha.20+1.17-rc2.jar"
  fabric-api = "https://www.brekitomasson.com/fettlol/mods/fabric-api-0.34.9+1.17.jar"
  fabric-language-kotlin = "https://www.brekitomasson.com/fettlol/mods/fabric-language-kotlin-1.5.0+kotlin.1.4.31.jar"
  fallingleaves = "https://www.brekitomasson.com/fettlol/mods/fallingleaves-1.7.0+1.17.jar"
  fallingtree = "https://www.brekitomasson.com/fettlol/mods/FallingTree-1.17-2.11.4.jar"
  fettlol-utilmod = "https://www.brekitomasson.com/fettlol/mods/FettLolUtilMod-1.1.0+1.17.jar"
  geckolib = "https://www.brekitomasson.com/fettlol/mods/geckolib-fabric-1.17-3.0.5.jar"
  infinitywaterbucket = "https://www.brekitomasson.com/fettlol/mods/infinity-water-bucket-1.4-mc1.17-fabric.jar"
  keepheadnames = "https://www.brekitomasson.com/fettlol/mods/KeepHeadNames-1.3.jar"
  krypton = "https://www.brekitomasson.com/fettlol/mods/krypton-0.1.3.jar"
  lambdynamiclights = "https://www.brekitomasson.com/fettlol/mods/lambdynamiclights-2.0.0+1.17.jar"
  lithium = "https://www.brekitomasson.com/fettlol/mods/lithium-fabric-mc1.17-0.7.0.jar"
  moreberries = "https://www.brekitomasson.com/fettlol/mods/moreberries-1.4.0.jar"
  overhauled-overworld = "https://www.brekitomasson.com/fettlol/mods/WilliamWythersOverhauledOverworld1.17.jar"
  presence-footsteps = "https://www.brekitomasson.com/fettlol/mods/PresenceFootsteps-r31-1.17-rc1.jar"
  ringofattraction = "https://www.brekitomasson.com/fettlol/mods/RingOfAttraction-Fabric-1.17-1.1.7.jar"
  riverredux = "https://www.brekitomasson.com/fettlol/mods/riverredux-0.2.0.jar"
  taxfreelevels = "https://www.brekitomasson.com/fettlol/mods/TaxFreeLevels-1.2.jar"
  villagernames = "https://www.brekitomasson.com/fettlol/mods/villagernames-1.17-2.0.0.jar"
  voxelmap = "https://www.brekitomasson.com/fettlol/mods/fabricmod_VoxelMap-1.10.15_for_1.17.0.jar"

[dev]
