manifestVersion = 0

[package]
  type = "modpack"
  name = "fettlol"
  description = "The Fettlol Modpack, an opinionated Vanilla++ Experience."
  version = "1.14.3"
  platform = "fabric"
  license = "MIT"
  author = "Breki Tomasson <breki.tomasson@gmail.com>"

[requirements]
  minecraft = "1.17"
  fabric = "*"

[dependencies]
architectury = "https://www.brekitomasson.com/fettlol/mods/architectury-2.0.7-fabric.jar"
autopath = "https://www.brekitomasson.com/fettlol/mods/autopath-mc1.17-1.4.2.jar"
builtin-servers = "https://www.brekitomasson.com/fettlol/mods/builtin-servers-1.0.1-BETA+1.17.jar"
coloredslime = "https://www.brekitomasson.com/fettlol/mods/coloredslime-1.2.2+1.17.jar"
croptopia = "https://www.brekitomasson.com/fettlol/mods/Croptopia-1.17-rc2-FABRIC-1.4.1.jar"
dankstorage = "https://www.brekitomasson.com/fettlol/mods/dankstorage-2.0-1.17-rc1.jar"
ducts = "https://www.brekitomasson.com/fettlol/mods/ducts-1.1.0.jar"
earth2java = "https://www.brekitomasson.com/fettlol/mods/Earth2Java-1.7.1+1.17.jar"
emotecraft = "https://www.brekitomasson.com/fettlol/mods/emotecraft-for-MC1.17-rc2-2.0.5-fabric.jar"
expandedstorage = "https://www.brekitomasson.com/fettlol/mods/expandedstorage-7.0.0-alpha.20+1.17-rc2.jar"
fabric-api = "https://www.brekitomasson.com/fettlol/mods/fabric-api-0.34.9+1.17.jar"
fabric-language-kotlin = "https://www.brekitomasson.com/fettlol/mods/fabric-language-kotlin-1.5.0+kotlin.1.4.31.jar"
fallingleaves = "https://www.brekitomasson.com/fettlol/mods/fallingleaves-1.7.0+1.17.jar"
fallingtree = "https://www.brekitomasson.com/fettlol/mods/FallingTree-1.17-2.11.4.jar"
fettlol-utilmod = "https://www.brekitomasson.com/fettlol/mods/FettLolUtilMod-1.1.0+1.17.jar"
geckolib = "https://www.brekitomasson.com/fettlol/mods/geckolib-fabric-1.17-3.0.5.jar"
infinitywaterbucket = "https://www.brekitomasson.com/fettlol/mods/infinity-water-bucket-1.4-mc1.17-fabric.jar"
krypton = "https://www.brekitomasson.com/fettlol/mods/krypton-0.1.3.jar"
lambdynamiclights = "https://www.brekitomasson.com/fettlol/mods/lambdynamiclights-2.0.0+1.17.jar"
lithium = "https://www.brekitomasson.com/fettlol/mods/lithium-fabric-mc1.17-0.7.0.jar"
moreberries = "https://www.brekitomasson.com/fettlol/mods/moreberries-1.4.0.jar"
presence-footsteps = "https://www.brekitomasson.com/fettlol/mods/PresenceFootsteps-r31-1.17-rc1.jar"
riverredux = "https://www.brekitomasson.com/fettlol/mods/riverredux-0.2.0.jar"
villagernames = "https://www.brekitomasson.com/fettlol/mods/villagernames-1.17-2.0.0.jar"
voxelmap = "https://www.brekitomasson.com/fettlol/mods/fabricmod_VoxelMap-1.10.15_for_1.17.0.jar"
overhauled-overworld = "https://www.brekitomasson.com/fettlol/mods/WilliamWythersOverhauledOverworld1.17.jar"
taxfreelevels = "https://www.brekitomasson.com/fettlol/mods/TaxFreeLevels-1.2.jar"
keepheadnames = "https://www.brekitomasson.com/fettlol/mods/KeepHeadNames-1.3.jar"
axesareweapons = "https://www.brekitomasson.com/fettlol/mods/AxesAreWeapons-1.2-1.17.jar"
ringofattraction = "https://www.brekitomasson.com/fettlol/mods/RingOfAttraction-Fabric-1.17-1.1.7.jar"


#  adorn = "^1.14.0-0.mpkg.2.beta.1"
#  advancements-debug = "^2.2.0-0.mpkg.1"
#  advancements-enlarger = "^0.2.3-0.mpkg.1"
#  alaska-nativecraft = "https://www.brekitomasson.com/fettlol/mods/alaskanativecraft-1.2.2.jar"
#  amecs = "^1.3.4-0.mpkg.1"
#  appleskin = "^1.0.11"
#  appliedenergistics = ""
#  battle-towers = "^3.3.4"
#  bedspreads = "^1.3.1-0.mpkg.1"
#  better-dropped-items = "^1.2.4-0.minepkg.1"
#  better-enchanted-books = "^1.2.7-0.mpkg.1"
#  better-ping-display = "^1.1.0-0.mpkg.1"
#  betterend = "https://www.brekitomasson.com/fettlol/mods/better-end-0.9.5-pre.jar"
#  betternether = "^5.0.8"
#  biome-makeover = "https://www.brekitomasson.com/fettlol/mods/biome-makeover-1.16.5-1.3.8.jar"
#  blame = "^1.16.5-0.mpkg.1.3.0.1"
#  blur = "^2.1.0-0.mpkg.1"
#  breakprogress = "https://www.brekitomasson.com/fettlol/mods/breakprogress-1.0.1.jar"
#  byg = "https://www.brekitomasson.com/fettlol/mods/byg-1.1.8.jar"
#  cca = "^2.8.2-0.mpkg.1"
#  charm = "^2.3.2-0.mpkg.1"
#  chat-heads = "^0.2.2-0.mpkg.1"
#  chillager = "^1.1.0-0.mpkg.1"
#  cinderscapes = "^1.3.3-0.mpkg.1"
#  clear-skies = "^1.5.57-0.mpkg.2.snapshot+0208"
#  cloth-config = "https://www.brekitomasson.com/fettlol/mods/cloth-config-4.11.26-fabric.jar"
#  cotton = "^1.1.0-0.mpkg.1"
#  crimsonmoon = "^2.0.4-0.mpkg.1"
#  curios = "^0.0.13-0.mpkg.1+0509"
#  damagetilt = "^0.1.2-0.mpkg.1"
#  dark-loading-screen = "^1.6.3-0.mpkg.1"
#  discerning-furnace = "^1.0.1-0.mpkg.1"
#  expanded-concrete = ""
#  extra-generators = "^1.0.1-0.mpkg.1.BETA"
#  fadeinchunks = "^1.0.0-0.mpkg.2"
#  flonters = "^1.1.1-0.mpkg.1"
#  flora-doubling = "^1.3.0-0.mpkg.1"
#  gentlefawn = "https://www.brekitomasson.com/fettlol/mods/GentleFawn-1.1.4-MC1.16.5-fabric.jar"
#  gilded-netherite = "https://www.brekitomasson.com/fettlol/mods/gilded-netherite-fabric-1.6.0.jar"
#  go-fish = "https://www.brekitomasson.com/fettlol/mods/go-fish-1.2.3-beta-1.16.5.jar"
#  horseinfo = "^0.2.2-0.mpkg.1"
#  horsestatsvanilla = "^4.1.7-0.mpkg.1"
#  illuminations = "https://www.brekitomasson.com/fettlol/mods/illuminations-1.5.jar"
#  indium = "^1.0.0-0.mpkg.1"
#  inventory-profiles = "^0.4.2-0.mpkg.1"
#  lifts = "^1.1.0"
#  lightoverlay = "^5.8.0-0.mpkg.1"
#  lonsdaleite = "^1.0.15-0.mpkg.1"
#  mcdunegeonsweapons = "https://www.brekitomasson.com/fettlol/mods/mcdw-3.2.0.jar"
#  mcdungeonsarmors = "https://www.brekitomasson.com/fettlol/mods/mcda-1.5.0.jar"
#  midas-hunger = "https://www.brekitomasson.com/fettlol/mods/midas-hunger-1.3.2.jar"
#  miskatonicmysteries = "^0.0.5-0.mpkg.1+fix22"
#  mixintrace = "^1.0.0-0.mpkg.1"
#  mob-farm-helpers = "^1.4.2-0.mpkg.1"
#  modmenu = "^1.16.9-0.mpkg.2"
#  morediscs = "https://www.brekitomasson.com/fettlol/mods/more-discs-1.0.4.jar"
#  morepaths = "https://www.brekitomasson.com/fettlol/mods/more-paths-0.0.3.jar"
#  mostructures = "^1.2.0-0.mpkg.2+0426"
#  netherite-horse-armor = "^1.1.0-0.mpkg.1"
#  not-enough-animations = "https://www.brekitomasson.com/fettlol/mods/notenoughanimations-1.2.4.jar"
#  notenoughcrashes = "^3.2.0-0.mpkg.1"
#  npcvariety = "^1.2.4"
#  okzoomer = "^4.0.1-0.mpkg.1"
#  patchouli = "^1.16.4-0.mpkg.2.50"
#  perfectaccuracy = "^1.0.1"
#  polymorph = "^0.0.10-0.mpkg.1+0131"
#  quick-shulker = "https://www.brekitomasson.com/fettlol/mods/quickshulker-1.1.12-1.16.jar"
#  randompatches = "^2.4.5-0.mpkg.1+fixes220"
#  repurposed-structures = "https://www.brekitomasson.com/fettlol/mods/repurposed_structures-1.16.5-1.11.0-fabric.jar"
#  reroll = "^1.2.1"
#  roughlyenoughitems = "^5.11.0-0.mpkg.1"
#  seasons = "^1.2.0-0.mpkg.BETA"
#  show-off = "^1.0.0"
#  simplyimprovedterrain = "https://www.brekitomasson.com/fettlol/mods/SimplyImprovedTerrain-0.3.2.1-Fabric.jar"
#  slapmap = "^1.0.1-0.mpkg.1"
#  slimyfloor = "https://www.brekitomasson.com/fettlol/mods/slimyfloor-1.0.0%2B1.16.x.jar"
#  sodium = "^0.1.1-next.3"
#  spark = "^1.5.2-0.mpkg.1"
#  starlight = "^1.0.0-0.mpkg.1.RC2"
#  stoneholm = "https://www.brekitomasson.com/fettlol/mods/stoneholm-1.2.2.jar"
#  techreborn = "^3.8.2"
#  terrestria = "^2.2.0-0.mpkg.1"
#  tinytweaks = "https://www.brekitomasson.com/fettlol/mods/tinytweaks-1.2.3.jar"
#  transliterationlib = "^1.0.4-0.mpkg.1"
#  traverse = "^3.3.2"
#  trinkets = "^2.6.7-0.mpkg.1"
#  truedarkness = "^1.6.0-0.mpkg.1"
#  untitledduckmod = "^0.2.2-0.mpkg.1"
#  villagerhats = "^1.0.1-0.mpkg.1"
#  vistas = "^1.3.0-0.mpkg.1"
#  waystones = "^1.1.1-0.mpkg.2.1"
#  wild-world = "^2.0.0-0.mpkg.1"
#  winged = "https://www.brekitomasson.com/fettlol/mods/winged-1.16.2-1.4.1.jar"
#  wolveswitharmor = "^1.5.4"
#  wthit = "^2.10.0-0.mpkg.1"
#  xaeros-minimap = "https://www.brekitomasson.com/fettlol/mods/Xaeros_Minimap_21.8.2_Fabric_1.16.5.jar"
#  xaeros-worldmap = "https://www.brekitomasson.com/fettlol/mods/XaerosWorldMap_1.14.1_Fabric_1.16.5.jar"

# variable spawner hardness
# fat XP orbs (no longer needed due to v1.17?)

[dev]
