manifestVersion = 0

[package]
  type = "modpack"
  name = "fettlol"
  description = "The Fettlol Modpack, an opinionated Vanilla++ Experience."
  version = "1.14.4"
  platform = "fabric"
  license = "MIT"
  author = "Breki Tomasson <breki.tomasson@gmail.com>"

[requirements]
  minecraft = "1.17"
  fabric = "*"

[dependencies]
  advancements-debug = "https://www.brekitomasson.com/fettlol/mods/1.17/advdebug-2.3.0.jar"
  amecs = "https://www.brekitomasson.com/fettlol/mods/1.17/amecs-1.3.4+mc.1.17.jar"
  appleskin = "https://www.brekitomasson.com/fettlol/mods/1.17/appleskin-fabric-mc1.17-2.0.0.jar"
  architectury = "https://www.brekitomasson.com/fettlol/mods/1.17/architectury-2.1.20-fabric.jar"
  autopath = "https://www.brekitomasson.com/fettlol/mods/1.17/autopath-mc1.17-1.4.3.jar"
  axesareweapons = "https://www.brekitomasson.com/fettlol/mods/1.17/AxesAreWeapons-1.2-1.17.jar"
  bedspreads = "https://www.brekitomasson.com/fettlol/mods/1.17/bedspreads-fabric-1.4.0-1.17.jar"
  beenfo = "https://www.brekitomasson.com/fettlol/mods/1.17/beenfo-1.17-fabric0.34.9-1.3.2.jar"
  better-dropped-items = "https://www.brekitomasson.com/fettlol/mods/1.17/betterdroppeditems-1.3.0-1.17.jar"
  betternether = "https://www.brekitomasson.com/fettlol/mods/1.17/better-nether-5.1.0.jar"
  blame = "https://www.brekitomasson.com/fettlol/mods/1.17/blame-1.17-4.0.0-fabric.jar"
  blur = "https://www.brekitomasson.com/fettlol/mods/1.17/Blur-2.2.0-1.17+fabric.jar"
  byg = "https://www.brekitomasson.com/fettlol/mods/1.17/byg-1.1.8-BETA.jar"
  capes = "https://www.brekitomasson.com/fettlol/mods/1.17/capes-1.2.0.jar"
  charm = "https://www.brekitomasson.com/fettlol/mods/1.17/charm-fabric-1.17-3.2.3-beta.jar"
  clear-skies = "https://www.brekitomasson.com/fettlol/mods/1.17/clear-skies-mc117-1.5.69.jar"
  cloth-config = "https://www.brekitomasson.com/fettlol/mods/1.17/cloth-config-5.0.34-fabric.jar"
  coloredslime = "https://www.brekitomasson.com/fettlol/mods/1.17/coloredslime-1.2.2+1.17.jar"
  compressed = "https://www.brekitomasson.com/fettlol/mods/1.17/compressed-fabric-1.3.1.jar"
  croptopia = "https://www.brekitomasson.com/fettlol/mods/1.17/Croptopia-1.17-FABRIC-1.5.0.jar"
  damagetilt = "https://www.brekitomasson.com/fettlol/mods/1.17/DamageTilt-1.17-fabric-0.1.2.jar"
  dankstorage = "https://www.brekitomasson.com/fettlol/mods/1.17/dankstorage-2.0a-1.17.jar"
  dark-loading-screen = "https://www.brekitomasson.com/fettlol/mods/1.17/dark-loading-screen-1.6.5.jar"
  defaultsettings = "https://www.brekitomasson.com/fettlol/mods/1.17/DefaultSettings-1.17.x-3.0.2.jar"
  discerning-furnace = "https://www.brekitomasson.com/fettlol/mods/1.17/discerning-furnace-1.0.2+MC1.17.jar"
  ducts = "https://www.brekitomasson.com/fettlol/mods/1.17/ducts-1.1.1.jar"
  earth2java = "https://www.brekitomasson.com/fettlol/mods/1.17/Earth2Java-1.7.1+1.17.jar"
  easy-feed = "https://www.brekitomasson.com/fettlol/mods/1.17/mcf-easyfeed-1.3.0-1.17.jar"
  emotecraft = "https://www.brekitomasson.com/fettlol/mods/1.17/emotecraft-for-MC1.17-2.0.7-fabric.jar"
  expandedstorage = "https://www.brekitomasson.com/fettlol/mods/1.17/expandedstorage-7.0.0-alpha.33+1.17.jar"
  extra-generators = "https://www.brekitomasson.com/fettlol/mods/1.17/extra-generators-1.0.6-BETA+1.17.jar"
  fabric-api = "https://www.brekitomasson.com/fettlol/mods/1.17/fabric-api-0.36.0+1.17.jar"
  fabric-language-kotlin = "https://www.brekitomasson.com/fettlol/mods/1.17/fabric-language-kotlin-1.6.2+kotlin.1.5.20.jar"
  fallingleaves = "https://www.brekitomasson.com/fettlol/mods/1.17/fallingleaves-1.7.0+1.17.jar"
  fallingtree = "https://www.brekitomasson.com/fettlol/mods/1.17/FallingTree-1.17-2.12.1.jar"
  fettlol-utilmod = "https://www.brekitomasson.com/fettlol/mods/1.17/FettLolUtilMod-1.1.2+1.17.jar"
  flonters = "https://www.brekitomasson.com/fettlol/mods/1.17/Flonters-1.2.0+1.17.jar"
  geckolib = "https://www.brekitomasson.com/fettlol/mods/1.17/geckolib-fabric-1.17-3.0.5.jar"
  grizzlybear = "https://www.brekitomasson.com/fettlol/mods/1.17/grizzlybear-1.1.1.jar"
  horseinfo = "https://www.brekitomasson.com/fettlol/mods/1.17/hwyla-addon-horseinfo-0.3.0-1.17.jar"
  horsestatsvanilla = "https://www.brekitomasson.com/fettlol/mods/1.17/horse-stats-vanilla-4.1.8.jar"
  infinitywaterbucket = "https://www.brekitomasson.com/fettlol/mods/1.17/infinity-water-bucket-1.4-mc1.17-fabric.jar"
  inventory-profiles = "https://www.brekitomasson.com/fettlol/mods/1.17/InventoryProfilesNext-fabric-1.17-0.8.1.jar"
  iris = "https://www.brekitomasson.com/fettlol/mods/1.17/iris-mc1.17-1.1.0.jar"
  keepheadnames = "https://www.brekitomasson.com/fettlol/mods/1.17/KeepHeadNames-1.3.jar"
  krypton = "https://www.brekitomasson.com/fettlol/mods/1.17/krypton-0.1.3.jar"
  lambdynamiclights = "https://www.brekitomasson.com/fettlol/mods/1.17/lambdynamiclights-2.0.1+1.17.jar"
  lightoverlay = "https://www.brekitomasson.com/fettlol/mods/1.17/light-overlay-6.0.0-fabric.jar"
  lithium = "https://www.brekitomasson.com/fettlol/mods/1.17/lithium-fabric-mc1.17-0.7.2.jar"
  mcdunegeonsweapons = "https://www.brekitomasson.com/fettlol/mods/1.17/mcdw-3.2.3.jar"
  mcdungeonsarmors = "https://www.brekitomasson.com/fettlol/mods/1.17/mcda-1.6.4.jar"
  midas-hunger = "https://www.brekitomasson.com/fettlol/mods/1.17/midas-hunger-1.4.0.jar"
  modmenu = "https://www.brekitomasson.com/fettlol/mods/1.17/modmenu-2.0.2.jar"  
  more-axolotl-variants = "https://www.brekitomasson.com/fettlol/mods/1.17/mavm-1.0.2b.jar"
  moreberries = "https://www.brekitomasson.com/fettlol/mods/1.17/moreberries-1.4.2.jar"
  morevillagers = "https://www.brekitomasson.com/fettlol/mods/1.17/morevillagers-FABRIC-1.17-2.0.1.jar"
  mostructures = "https://www.brekitomasson.com/fettlol/mods/1.17/mostructures-1.2.1-1.17.jar"
  nether-chest = "https://www.brekitomasson.com/fettlol/mods/1.17/netherchest-mc1.17.x-2.0.jar"
  not-enough-animations = "https://www.brekitomasson.com/fettlol/mods/1.17/notenoughanimations-1.3.0.jar"
  notenoughcrashes = "https://www.brekitomasson.com/fettlol/mods/1.17/notenoughcrashes-3.3.1+1.17-fabric.jar"
  npcvariety = "https://www.brekitomasson.com/fettlol/mods/1.17/npc-variety-1.17.0-2.1.0.jar"
  okzoomer = "https://www.brekitomasson.com/fettlol/mods/1.17/okzoomer-5.0.0-beta.2+1.17.jar"
  overhauled-overworld = "https://www.brekitomasson.com/fettlol/mods/1.17/WilliamWythersOverhauledOverworld1.17.jar"
  overhauled-overworld-cavescliffs = "https://www.brekitomasson.com/fettlol/mods/1.17/CavesAndCliffsAddOnForWilliamWythersOverhauledOverworld-1.1.jar"
  overhauled-overworld-primordial = "https://www.brekitomasson.com/fettlol/mods/1.17/Primordial+Shores+add-on+for+William+Wythers+Overhauled+Overworld.jar"
  overhauled-overworld-structures = "https://www.brekitomasson.com/fettlol/mods/1.17/MoreStructuresForWilliamWythersOverhauledOverworld-1.1.jar"
  packages = "https://www.brekitomasson.com/fettlol/mods/1.17/packages-1.17-1.2.0.jar"
  perfectaccuracy = "https://www.brekitomasson.com/fettlol/mods/1.17/PerfectAccuracy-1.1-1.17.jar"
  presence-footsteps = "https://www.brekitomasson.com/fettlol/mods/1.17/PresenceFootsteps-r31-1.17-rc1.jar"
  repurposed-structures = "https://www.brekitomasson.com/fettlol/mods/1.17/repurposed_structures_fabric-2.0.3+1.17.0.jar"
  rightclickharvest = "https://www.brekitomasson.com/fettlol/mods/1.17/rightclickharvest-1.3.0.jar"
  ringofattraction = "https://www.brekitomasson.com/fettlol/mods/1.17/RingOfAttraction-Fabric-1.17-1.1.10.jar"
  riverredux = "https://www.brekitomasson.com/fettlol/mods/1.17/riverredux-0.2.0.jar"
  roughlyenoughitems = "https://www.brekitomasson.com/fettlol/mods/1.17/RoughlyEnoughItems-6.0.262-alpha-fabric.jar"
  seasons = "https://www.brekitomasson.com/fettlol/mods/1.17/fabric-seasons-1.2.2-BETA+1.17.jar"
  spark = "https://www.brekitomasson.com/fettlol/mods/1.17/spark-fabric.jar"
  spawnermod = "https://www.brekitomasson.com/fettlol/mods/1.17/fabric-branders-spawnermod-1.17-1.1.1.jar"
  stickyhopper = "https://www.brekitomasson.com/fettlol/mods/1.17/stickyhopper-2.3-1.17-1.jar"
  stoneholm = "https://www.brekitomasson.com/fettlol/mods/1.17/stoneholm-1.3.jar"
  taxfreelevels = "https://www.brekitomasson.com/fettlol/mods/1.17/TaxFreeLevels-1.2.jar"
  techreborn = "https://www.brekitomasson.com/fettlol/mods/1.17/TechReborn-5.0.3-beta+build.55.jar"
  transliterationlib = "https://www.brekitomasson.com/fettlol/mods/1.17/TRansliterationLib-1.1.0.jar"
  truedarkness = "https://www.brekitomasson.com/fettlol/mods/1.17/darkness-mc117-1.6.73.jar"
  villagernames = "https://www.brekitomasson.com/fettlol/mods/1.17/villagernames-1.17-2.0.0.jar"
  vistas = "https://www.brekitomasson.com/fettlol/mods/1.17/vistas-1.3.3.jar"
  voicechat = "https://www.brekitomasson.com/fettlol/mods/1.17/voicechat-1.17-1.2.3.jar"
  waystones = "https://www.brekitomasson.com/fettlol/mods/1.17/wraith-waystones-2.0.1.jar"
  wolveswitharmor = "https://www.brekitomasson.com/fettlol/mods/1.17/wolves-with-armor-1.6.0-1.17.jar"
  wthit = "https://www.brekitomasson.com/fettlol/mods/1.17/wthit-fabric-3.6.1.jar"
  xaeros-minimap = "https://www.brekitomasson.com/fettlol/mods/1.17/Xaeros_Minimap_21.12.5_Fabric_1.17.jar"
  xaeros-worldmap = "https://www.brekitomasson.com/fettlol/mods/1.17/XaerosWorldMap_1.14.5.1_Fabric_1.17.jar"

[dev]
