manifestVersion = 0

[package]
  type = "modpack"
  name = "fettlol"
  description = "The Fettlol Modpack, an opinionated Vanilla++ Experience."
  version = "1.12.1"
  platform = "fabric"
  license = "MIT"
  author = "Breki Tomasson <breki.tomasson@gmail.com>"

[requirements]
  minecraft = "1.16.5"
  fabric = "*"

[dependencies]
  adorn = "^1.14.0-0.mpkg.1.beta"
  advancements-debug = "^2.2.0-0.mpkg.1"
  advancements-enlarger = "^0.2.3-0.mpkg.1"
  alaska-nativecraft = "^1.1.2-0.mpkg.1"
  amecs = "^1.3.4-0.mpkg.1"
  appleskin = "^1.0.11"
  appliedenergistics2 = "^8.2.0-0.mpkg.2.alpha.3"
  architectury = "^1.11.0-0.mpkg.1"
  axesareweapons = "^1.1.1"
  battle-towers = "^3.3.4"
  bedspreads = "^1.3.1-0.mpkg.1"
  better-dropped-items = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/betterdroppeditems-1.2.4-1.16.2.jar"
  better-enchanted-books = "^1.2.5-0.mpkg.1"
  better-ping-display = "^1.1.0-0.mpkg.1"
  betterend = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/better-end-0.9.5-pre.jar"
  betternether = "^5.0.8"
  biome-makeover = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/biome-makeover-1.16.5-1.3.8.jar"
  blame = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/blame-1.16.4-2.4.1.jar"
  blur = "^2.1.0-0.mpkg.1"
  breakprogress = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/breakprogress-1.0.1.jar"
  byg = "^1.1.7-0.mpkg.1"
  cardinal-components-api = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/Cardinal-Components-API-2.8.2.jar"
  charm = "^2.3.2-0.mpkg.1"
  chat-heads = "^0.2.2-0.mpkg.1"
  chillager = "^1.1.0-0.mpkg.1"
  cinderscapes = "^1.3.3-0.mpkg.1"
  clear-skies = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/clear-skies-mc116-1.5.55.jar"
  coloredslime = "^1.1.7"
  cotton = "^1.1.0-0.mpkg.1"
  crimson-moon = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/crimson-moon-2.0.4-1.16.5.jar"
  croptopia = "^1.3.2-0.mpkg.1"
  curios = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/curios-fabric-0.0.11-1.16.4.jar"
  damage-tilt = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/DamageTilt-1.16-fabric-0.1.2.jar"
  dankstorage = "^1.9.0-0.mpkg.1"
  dark-loading-screen = "^1.6.3-0.mpkg.1"
  discerning-furnace = "^1.0.1-0.mpkg.1"
  ducts = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/ducts-1.0.4.jar"
  earth2java = "^1.6.1-0.mpkg.1"
  emotecraft = "^2.0.2-0.mpkg.1"
  expanded-concrete = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/expanded-concrete-0.0.2.jar"
  expandedstorage = "^5.6.33-0.mpkg.1"
  extra-generators = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/extragenerators-1.16.5-1.0.1-BETA.jar"
  fabric-language-kotlin = "^1.4.31-0.mpkg.1"
  fadeinchunks = "^1.0.0-0.mpkg.2"
  falling-tree = "^2.11.0-0.mpkg.1"
  fallingleaves = "^1.6.0"
  fatxporbs = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/fatxporbs-0.0.9%2B1.16.4.jar"
  fettlol-utilmod = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/FettLolUtilMod-1.0.12%2B1.16.5.jar"
  flonters = "^1.1.1-0.mpkg.1"
  flora-doubling = "^1.3.0-0.mpkg.1"
  geckolib = "^3.0.33-0.mpkg.1"
  gentlefawn = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/GentleFawn-1.1.4-MC1.16.5-fabric.jar"
  gilded-netherite = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/gilded-netherite-fabric-1.6.0.jar"
  go-fish = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/go-fish-1.2.1-beta-1.16.4.jar"
  horseinfo = "^0.2.2-0.mpkg.1"
  horsestatsvanilla = "^4.1.7-0.mpkg.1"
  illuminations = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/illuminations-1.5.jar"
  indium = "^1.0.0-0.mpkg.1"
  infinitywaterbucket = "^1.3.0-0.mpkg.1"
  inventory-profiles = "^0.4.2-0.mpkg.1"
  keepheadnames = "^1.2.1"
  lambdynamiclights = "^1.3.4"
  lifts = "^1.0.5-0.mpkg.1.beta"
  lightoverlay = "^5.8.0-0.mpkg.1"
  lithium = "^0.6.4-next"
  lonsdaleite = "^1.0.15-0.mpkg.1"
  mcdungeonsarmors = "^1.4.1-0.mpkg.1"
  mcdw = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/mcdw-3.1.2.jar"
  mdg = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/MDG%2B-%2B2.0.1%2B(FABRIC).jar"
  midas-hunger = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/midas-hunger-1.3.2.jar"
  minepkg-companion = "latest"
  miskatonic-mysteries = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/miskatonicmysteries-0.0.4.jar"
  mixin-trace = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/mixintrace-1.0.0.jar"
  mob-farm-helpers = "^1.4.2-0.mpkg.1"
  modmenu = "^1.16.9-0.mpkg.2"
  moreberries = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/moreberries-1.3.5.jar"
  morediscs = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/more-discs-1.0.4.jar"
  morepaths = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/more-paths-0.0.3.jar"
  mostructures = "^1.2.0-0.mpkg.1"
  netherite-horse-armor = "^1.1.0-0.mpkg.1"
  not-enough-animations = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/notenoughanimations-1.2.4.jar"
  not-enough-crashes = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/notenoughcrashes-3.2.0-fabric.jar"
  npc-variety = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/npc-variety-1.16.4-1.2.3.jar"
  okzoomer = "^4.0.1-0.mpkg.1"
  patchouli = "^1.16.4-0.mpkg.2.50"
  perfectaccuracy = "^1.0.1"
  phosphor = "^0.7.1-0.mpkg.1"
  polymorph = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/polymorph-fabric-0.0.10-1.16.5.jar"
  precense-footsteps = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/PresenceFootsteps-r28%2B1.16.2.jar"
  quick-shulker = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/quickshulker-1.1.12-1.16.jar"
  randompatches = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/randompatches-2.4.5-fabric.jar"
  repurposed-structures = "^1.9.0-0.mpkg.1"
  reroll = "^1.2.1"
  ringofattraction = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/RingOfAttraction-Fabric_1.16.5-1.0.29.jar"
  roughlyenoughitems = "^5.11.0-0.mpkg.1"
  show-off = "^1.0.0"
  slapmap = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/slapmap-1.0.1.jar"
  slimyfloor = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/slimyfloor-1.0.0%2B1.16.x.jar"
  sodium = "^0.1.1-next.3"
  spark = "^0.0.0-0.mpkg.1"
  stoneholm = "^1.0.1-0.mpkg.2"
  taxfreelevels = "^1.1.1"
  techreborn = "^3.8.2"
  terrestria = "^2.2.0-0.mpkg.1"
  tinytweaks = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/tinytweaks-1.2.3.jar"
  transliterationlib = "^1.0.4-0.mpkg.1"
  traverse = "^3.3.2"
  trinkets = "^2.6.7-0.mpkg.1"
  truedarkness = "^1.6.0-0.mpkg.1"
  untitledduckmod = "^0.1.2-0.mpkg.1"
  variable-spawner-hardness = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/VariableSpawnerHardness-1.16.5-1.2.jar"
  villagerhats = "^1.0.1-0.mpkg.1"
  villagernames = "^1.5.2-0.mpkg.1"
  vistas = "^1.3.0-0.mpkg.1"
  waystones = "^1.1.1-0.mpkg.1"
  wild-world = "^2.0.0-0.mpkg.1"
  winged = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/winged-1.16.2-1.4.1.jar"
  wolveswitharmor = "^1.5.4"
  woods-and-mires = "^1.1.0-0.mpkg.2"
  wthit = "^2.8.1-0.mpkg.3"
  xaeros-worldmap = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/XaerosWorldMap_1.13.4_Fabric_1.16.5.jar"
  xaeros-minimap = "https://github.com/FettLol/fettlol-modpack/raw/main/mods/Xaeros_Minimap_21.8.0_Fabric_1.16.5.jar"

[dev]
