[RSDungeonsConfig]
addDungeonsToModdedBiomes = true
blacklistedDungeonBiomes = ""

[RSDungeonsConfig.attemptsPerChunk]
badlandsDungeonAttemptsPerChunk = 8
darkForestDungeonAttemptsPerChunk = 8
desertDungeonAttemptsPerChunk = 8
jungleDungeonAttemptsPerChunk = 8
mushroomDungeonAttemptsPerChunk = 8
snowDungeonAttemptsPerChunk = 8
icyDungeonAttemptsPerChunk = 8
swampDungeonAttemptsPerChunk = 8
endDungeonAttemptsPerChunk = 8
netherDungeonAttemptsPerChunk = 8
oceanDungeonAttemptsPerChunk = 6

[RSDungeonsConfig.minHeight]
badlandsDungeonMinHeight = 2
darkForestDungeonMinHeight = 2
desertDungeonMinHeight = 2
jungleDungeonMinHeight = 2
mushroomDungeonMinHeight = 2
snowDungeonMinHeight = 2
icyDungeonMinHeight = 2
swampDungeonMinHeight = 2
endDungeonMinHeight = 2
netherDungeonMinHeight = 2
oceanDungeonMinHeight = 3

[RSDungeonsConfig.maxHeight]
badlandsDungeonMaxHeight = 255
darkForestDungeonMaxHeight = 255
desertDungeonMaxHeight = 255
jungleDungeonMaxHeight = 255
mushroomDungeonMaxHeight = 255
snowDungeonMaxHeight = 255
icyDungeonMaxHeight = 255
swampDungeonMaxHeight = 255
endDungeonMaxHeight = 255
netherDungeonMaxHeight = 255
oceanDungeonMaxHeight = 255
[RSMainConfig]
blacklistedDimensions = "the_bumblezone:the_bumblezone"
importModdedItems = true
blacklistedRSLoottablesFromImportingModdedItems = ""

[RSMainConfig.misc]
addBoulderToModdedBiomes = false
blacklistedBoulderBiomes = ""
boulderTiny = false
boulderGiant = false
diamondChanceInGiantBoulders = 7000
giantBouldersPerChunk = 0.5

[RSMainConfig.jungleFortress]
jungleFortressMaxChunkDistance = 32
addJungleFortressToModdedBiomes = true
blacklistedFortressBiomes = ""
silverfishSpawnrate = 0.25
lootChests = true

[RSMainConfig.igloos]
blacklistedIglooBiomes = ""
grassyIglooMaxChunkDistance = 20
addGrassyIglooToModdedBiomes = true
stoneIglooMaxChunkDistance = 20
addStoneIglooToModdedBiomes = true

[RSMainConfig.ruinedPortals]
blacklistedRuinedPortalsBiomes = ""
addRuinedPortalEndToModdedBiomes = true
ruinedPortalEndMaxChunkDistance = 120

[RSMainConfig.ruins]
blacklistedRuinsBiomes = ""
addRuinsNetherToModdedBiomes = true
ruinsNetherMaxChunkDistance = 35

[RSMainConfig.cities]
blacklistedCitiesBiomes = ""
addCityNetherToModdedBiomes = true
cityNetherMaxChunkDistance = 160
[RSTemplesConfig.temples]
blacklistedTempleBiomes = ""
netherWastelandTempleMaxChunkDistance = 30
addNetherWastelandTempleToModdedBiomes = true
netherBasaltTempleMaxChunkDistance = 30
addNetherBasaltTempleToModdedBiomes = true
netherCrimsonTempleMaxChunkDistance = 30
addNetherCrimsonTempleToModdedBiomes = true
netherWarpedTempleMaxChunkDistance = 30
addNetherWarpedTempleToModdedBiomes = true
netherSoulTempleMaxChunkDistance = 30
addNetherSoulTempleToModdedBiomes = true
[RSTemplesConfig.pyramids]
blacklistedPyramidBiomes = ""
netherPyramidMaxChunkDistance = 50
addNetherPyramidToModdedBiomes = true
badlandsPyramidMaxChunkDistance = 50
addBadlandsPyramidToModdedBiomes = true
pyramidSnowyMaxChunkDistance = 37
addPyramidSnowyToModdedBiomes = true
pyramidEndMaxChunkDistance = 68
addPyramidEndToModdedBiomes = true
pyramidIcyMaxChunkDistance = 37
addPyramidIcyToModdedBiomes = true
[RSMineshaftsConfig]
lootChestsMS = true
addMineshaftsToModdedBiomes = true
blacklistedMineshaftBiomes = ""

[RSMineshaftsConfig.spawnrate]
birchMineshaftSpawnrate = 25
jungleMineshaftSpawnrate = 25
desertMineshaftSpawnrate = 25
stoneMineshaftSpawnrate = 25
savannaMineshaftSpawnrate = 25
icyMineshaftSpawnrate = 25
oceanMineshaftSpawnrate = 25
taigaMineshaftSpawnrate = 25
swampAndDarkForestMineshaftSpawnrate = 25
endMineshaftSpawnrate = 0
netherMineshaftSpawnrate = 0
crimsonMineshaftSpawnrate = 40
warpedMineshaftSpawnrate = 40

[RSMineshaftsConfig.minHeight]
birchMineshaftMinHeight = 8
jungleMineshaftMinHeight = 8
desertMineshaftMinHeight = 8
stoneMineshaftMinHeight = 8
savannaMineshaftMinHeight = 8
icyMineshaftMinHeight = 8
oceanMineshaftMinHeight = 8
taigaMineshaftMinHeight = 8
swampAndDarkForestMineshaftMinHeight = 8
endMineshaftMinHeight = 30
netherMineshaftMinHeight = 8
crimsonMineshaftMinHeight = 8
warpedMineshaftMinHeight = 8

[RSMineshaftsConfig.maxHeight]
birchMineshaftMaxHeight = 40
jungleMineshaftMaxHeight = 40
desertMineshaftMaxHeight = 40
stoneMineshaftMaxHeight = 40
savannaMineshaftMaxHeight = 40
icyMineshaftMaxHeight = 40
oceanMineshaftMaxHeight = 40
taigaMineshaftMaxHeight = 40
swampAndDarkForestMineshaftMaxHeight = 40
endMineshaftMaxHeight = 37
netherMineshaftMaxHeight = 13
crimsonMineshaftMaxHeight = 13
warpedMineshaftMaxHeight = 13

[RSMineshaftsConfig.misc]
barrensIslandsEndMineshafts = false
[RSStrongholdsConfig]
strongholdSizeSH = 100.0
allowExtraSpawnersSH = true
lootChestsSH = true
turnOffVanillaStrongholds = true
blacklistedStrongholdBiomes = ""

[RSStrongholdsConfig.stonebrick]
allowStonebrickStrongholdToVanillaBiomes = true
addStonebrickStrongholdToModdedBiomes = true
silverfishSpawnrateSH = 0.25
stonebrickStrongholdMinHeight = 0
stonebrickStrongholdMaxHeight = 55
stonebrickStrongholdMaxChunkDistance = 75
stonebrickStrongholdChainSpawnrate = 35

[RSStrongholdsConfig.nether]
netherStrongholdMaxChunkDistance = 85
addNetherStrongholdToModdedBiomes = true
netherStrongholdMinHeight = 33
netherStrongholdMaxHeight = 36
netherStrongholdChainSpawnrate = 50
[RSOutpostsConfig]
blacklistedOutpostBiomes = ""

[RSOutpostsConfig.outposts]
netherBrickOutpostMaxChunkDistance = 45
addNetherBrickOutpostToModdedBiomes = true
warpedOutpostMaxChunkDistance = 45
addWarpedOutpostToModdedBiomes = true
crimsonOutpostMaxChunkDistance = 45
addCrimsonOutpostToModdedBiomes = true
addOutpostBirchToModdedBiomes = true
outpostBirchMaxChunkDistance = 55
addOutpostJungleToModdedBiomes = true
outpostJungleMaxChunkDistance = 55
addOutpostGiantTreeTaigaToModdedBiomes = true
outpostGiantTreeTaigaMaxChunkDistance = 55
addOutpostDesertToModdedBiomes = true
outpostDesertMaxChunkDistance = 55
addOutpostBadlandsToModdedBiomes = true
outpostBadlandsMaxChunkDistance = 55
addOutpostSnowyToModdedBiomes = true
outpostSnowyMaxChunkDistance = 55
addOutpostIcyToModdedBiomes = true
outpostIcyMaxChunkDistance = 55
addOutpostTaigaToModdedBiomes = true
outpostTaigaMaxChunkDistance = 45
addOutpostOakToModdedBiomes = true
outpostOakMaxChunkDistance = 45
outpostEndMaxChunkDistance = 61
addOutpostEndToModdedBiomes = true
[RSVillagesConfig]
addVillagesToModdedBiomes = true
blacklistedVillageBiomes = ""
badlandsVillageMaxChunkDistance = 44
birchVillageMaxChunkDistance = 44
darkForestVillageMaxChunkDistance = 55
jungleVillageMaxChunkDistance = 43
swampVillageMaxChunkDistance = 46
mountainsVillageMaxChunkDistance = 45
giantTaigaVillageMaxChunkDistance = 43
crimsonVillageMaxChunkDistance = 45
warpedVillageMaxChunkDistance = 45
villageOakMaxChunkDistance = 46
[RSWellsConfig]
addWellsToModdedBiomes = true
blacklistedWellBiomes = ""
canHaveBells = true

[RSWellsConfig.rarityPerChunk]
badlandsWellRarityPerChunk = 700
netherWellRarityPerChunk = 700
snowWellRarityPerChunk = 700
mossyStoneWellRarityPerChunk = 700
forestWellRarityPerChunk = 700
[RSShipwrecksConfig.blacklist]
blacklistedShipwreckBiomes = ""
addEndShipwreckToModdedBiomes = false
addNetherBricksShipwreckToModdedBiomes = true
addCrimsonShipwreckToModdedBiomes = true
addWarpedShipwreckToModdedBiomes = true
[RSShipwrecksConfig.maxChunkDistance]
endShipwreckMaxChunkDistance = 30
netherBricksShipwreckMaxChunkDistance = 50
crimsonShipwreckMaxChunkDistance = 40
warpedShipwreckMaxChunkDistance = 40
[RSMansionsConfig.blacklist]
blacklistedMansionBiomes = ""
addMansionBirchToModdedBiomes = false
addMansionJungleToModdedBiomes = true
addMansionOakToModdedBiomes = true
addMansionSavannaToModdedBiomes = true
addMansionTaigaToModdedBiomes = true
addMansionDesertToModdedBiomes = true
addMansionSnowyToModdedBiomes = true
[RSMansionsConfig.maxChunkDistance]
mansionBirchMaxChunkDistance = 1280
mansionJungleMaxChunkDistance = 1280
mansionOakMaxChunkDistance = 1280
mansionSavannaMaxChunkDistance = 1280
mansionTaigaMaxChunkDistance = 1280
mansionDesertMaxChunkDistance = 1280
mansionSnowyMaxChunkDistance = 1280
[RSWitchHutsConfig.blacklist]
blacklistedWitchHutsBiomes = ""
addWitchHutsOakToModdedBiomes = true
addWitchHutsTaigaToModdedBiomes = true
addWitchHutsBirchToModdedBiomes = true
addWitchHutsDarkForestToModdedBiomes = true
addWitchHutsGiantTreeTaigaToModdedBiomes = true
[RSWitchHutsConfig.maxChunkDistance]
witchHutsOakMaxChunkDistance = 68
witchHutsTaigaMaxChunkDistance = 68
witchHutsBirchMaxChunkDistance = 68
witchHutsDarkForestMaxChunkDistance = 68
witchHutsGiantTreeTaigaMaxChunkDistance = 68
